### ISSUE TITLE
about specular color

### ISSUE THREAD

**Issue by cv-lab-x** [ingra14m/Specular-Gaussians-MLP#2]
HI, thanks for your great work! since you have add mlps in the pipeline to render specular colors,  does the SIBR viewer work for your specular gaussians? what interactive viewer do you use for specular gaussians?
Looking forward to your reply, thanks! @ingra14m

**Comment by ingra14m** [comment]
Hi, the SIBR viewer is a highly customized viewer developed in C++, which poses significant challenges to the integration of MLPs. Consequently, I have no immediate plans to support real-time visualization based on the SIBR viewer. However, similar to the [Deformable-GS](https://github.com/ingra14m/Deformable-3D-Gaussians), we have developed a real-time viewer based on the DreamGaussian framework. This viewer is scheduled for release on November 17. 

By the way, this repository represents a preliminary attempt to address the limitations of 3D-GS in modeling specular highlights. It is hoped that this endeavor will bring attention to this issue and inspire future solutions.

**Comment by cv-lab-x** [comment]
thanks for your quick reply, yes, SH don't work well on specular colors, using mlps is one of the solutions. SG may be another solutions.

**Comment by ingra14m** [comment]
Out of goodwill, although I did not adapt SG in 3D-GS, I tested SG, [ASG](https://cg.cs.tsinghua.edu.cn/people/~kun/asg/), SH, MLP, and hybrid rendering in TensoRF. The results showed that only MLP and hybrid rendering can model specular effectively, and SG's performance was even worse than SH. 

Wishing you successful research.

**Comment by ingra14m** [comment]
This is the result of replacing SH with 16 SGs. No specular yet. 
![3wHRWlBnr0](https://github.com/ingra14m/Specular-Gaussians/assets/63096187/ad65cb30-3b09-4b3d-a3a1-2b6319a9415a)
